### ISSUE TITLE
Loading urls

### ISSUE THREAD

**Issue by amjadhassoun123123** [tmori/langchain_tutorial#1]
Can you explain how to load .url? whats the format? Can you give an example

**Comment by tmori** [comment]
> Can you explain how to load .url? whats the format? Can you give an example

Why don't you try this guide?

https://github.com/tmori/langchain_tutorial/blob/main/README.md#url-sample

Here is a sample of a url file:
https://github.com/tmori/langchain_tutorial/blob/main/urls/test.url

**Comment by amjadhassoun123123** [comment]
I get 
INFO: Storing Vector 
DB:urls/DB
Traceback (most recent call last):
File "/Users/Desktop/Projects/customChatBot/llama_index/PDF.py", line 273, in <module>
pdf_qa = create_db(doc_dir, db_dir, embedding_model, page_chunk_size)
File "/Users/Desktop/Projects/customChatBot/llama_index/PDF.py", line 97, in create_db
vectorstore = Chroma.from_documents(
File "/Users/miniforge3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 445, in from_documents
return cls.from_texts(
File "/Users/miniforge3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 413, in from_texts
chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
File "/Users/miniforge3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 160, in add_texts
self._collection.add(
File "/Users/miniforge3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 96, in add
ids, embeddings, metadatas, documents = self._validate_embedding_set(
File "/Users/miniforge3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 347, in _validate_embedding_set
ids = validate_ids(maybe_cast_one_to_many(ids))
File "/Users/miniforge3/lib/python3.10/site-packages/chromadb/api/types.py", line 97, in maybe_cast_one_to_many
if isinstance(target[0], (int, float)):
IndexError: list index out of range

**Comment by tmori** [comment]
Please provide more specific details about the operation. Also, please try checking if the GitHub repository is up to date.

**Comment by tmori** [comment]
The Python version and installed package versions are as follows:

$ python3 --version
Python 3.10.6

$ pip3 list
Package                 Version
----------------------- ---------------
aiohttp                 3.8.4
aiosignal               1.3.1
anyio                   3.7.0
argilla                 1.8.0
async-generator         1.10
async-timeout           4.0.2
attrs                   21.2.0
Automat                 20.2.0
Babel                   2.8.0
backoff                 2.2.1
bcrypt                  3.2.0
blinker                 1.4
certifi                 2023.5.7
cffi                    1.15.1
chardet                 4.0.0
charset-normalizer      3.1.0
chromadb                0.3.25
click                   8.0.3
clickhouse-connect      0.5.25
cloud-init              22.2
colorama                0.4.4
coloredlogs             15.0.1
command-not-found       0.3
commonmark              0.9.1
configobj               5.0.6
constantly              15.1.0
cryptography            41.0.0
dataclasses-json        0.5.7
dbus-python             1.2.18
Deprecated              1.2.14
distro                  1.7.0
distro-info             1.1build1
duckdb                  0.8.0
et-xmlfile              1.1.0
exceptiongroup          1.1.1
fastapi                 0.95.2
flatbuffers             23.5.26
frozenlist              1.3.3
greenlet                2.0.2
h11                     0.14.0
hnswlib                 0.7.0
httpcore                0.16.3
httplib2                0.20.2
httptools               0.5.0
httpx                   0.23.3
humanfriendly           10.0
hyperlink               21.0.0
idna                    3.3
importlib-metadata      4.6.4
incremental             21.3.0
jeepney                 0.7.1
Jinja2                  3.0.3
joblib                  1.2.0
jsonpatch               1.32
jsonpointer             2.0
jsonschema              3.2.0
keyring                 23.5.0
langchain               0.0.186
launchpadlib            1.10.16
lazr.restfulclient      0.14.4
lazr.uri                1.0.6
lxml                    4.9.2
lz4                     4.3.2
Markdown                3.4.3
MarkupSafe              2.0.1
marshmallow             3.19.0
marshmallow-enum        1.5.1
monotonic               1.6
more-itertools          8.10.0
mpmath                  1.3.0
msg-parser              1.2.0
multidict               6.0.4
mypy-extensions         1.0.0
netifaces               0.11.0
nltk                    3.8.1
numexpr                 2.8.4
numpy                   1.23.5
oauthlib                3.2.0
olefile                 0.46
onnxruntime             1.15.0
openai                  0.27.5
openapi-schema-pydantic 1.2.4
openpyxl                3.1.2
outcome                 1.2.0
overrides               7.3.1
packaging               23.1
pandas                  1.5.3
pdf2image               1.16.3
pdfminer                20191125
pdfminer.six            20221105
pexpect                 4.8.0
Pillow                  9.5.0
pip                     22.0.2
posthog                 3.0.1
protobuf                4.23.2
ptyprocess              0.7.0
pyasn1                  0.4.8
pyasn1-modules          0.2.1
pycparser               2.21
pycryptodome            3.18.0
pydantic                1.10.8
Pygments                2.15.1
PyGObject               3.42.1
PyHamcrest              2.0.2
PyJWT                   2.3.0
pyOpenSSL               21.0.0
pypandoc                1.11
pyparsing               2.4.7
pypdf                   3.9.0
pyrsistent              0.18.1
pyserial                3.5
PySocks                 1.7.1
python-apt              2.3.0+ubuntu2.1
python-dateutil         2.8.2
python-debian           0.1.43ubuntu1
python-docx             0.8.11
python-dotenv           1.0.0
python-magic            0.4.27
python-pptx             0.6.21
pytz                    2022.1
PyYAML                  5.4.1
regex                   2023.5.5
requests                2.31.0
rfc3986                 1.5.0
rich                    13.0.1
SecretStorage           3.3.1
selenium                4.9.1
service-identity        18.1.0
setuptools              59.6.0
six                     1.16.0
sniffio                 1.3.0
sortedcontainers        2.4.0
sos                     4.3
SQLAlchemy              2.0.15
ssh-import-id           5.11
starlette               0.27.0
sympy                   1.12
systemd-python          234
tabulate                0.9.0
tenacity                8.2.2
tiktoken                0.4.0
tokenizers              0.13.3
tqdm                    4.65.0
trio                    0.22.0
trio-websocket          0.10.2
Twisted                 22.1.0
typer                   0.9.0
typing_extensions       4.6.2
typing-inspect          0.9.0
tzdata                  2023.3
ubuntu-advantage-tools  27.11.2
ufw                     0.36.1
unattended-upgrades     0.1
unstructured            0.7.0
urllib3                 1.26.5
uvicorn                 0.22.0
uvloop                  0.17.0
wadllib                 1.3.6
watchfiles              0.19.0
websockets              11.0.3
wheel                   0.37.1
wrapt                   1.14.1
wsproto                 1.2.0
xlrd                    2.0.1
XlsxWriter              3.1.2
yarl                    1.9.2
zipp                    1.0.0
zope.interface          5.4.0
zstandard               0.21.0

**Comment by amjadhassoun123123** [comment]
Thanks, fixed
